version: "3.9"
services:
  app:
    build:
      context: .
      args:
        bundle: yarn run build
      dockerfile: docker/vue.dockerfile
    container_name: vue-vite-client
    image: vue-vite-client:1.0
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./logs:/app/logs:rw
    command: yarn run pm2/start
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: always
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
